### PR TITLE
Add GitHub hook integration

### PR DESCRIPTION
**Pull request by Davidsoff**
Fairly straightforward,

This PR adds the hook for GitHub Releases.

Additionally it also fixes a spelling mistake in one of the analytics urls/names `analaytics` -> `analytics`

### CODE REVIEW

**Comment by Davidsoff** [comment]
If this name/url change is undesirable I am happy to remove those changes from this PR

**Comment by MatthewJohn** [comment]
@Davidsoff 
First of all, I can't believe how many typos of analytics there are :D 
But, thank you so much for this - it all looks great :)

Couple of notes:
 - I'm sure you saw in the README/contributing, but the project might need to switch to another license (GPL or LGPL). Could you state a comment that you're happy if this happens and you agree that the changes you've contributed can also change in license to GPL/LGPL? :)
 - I think some unit tests would be needed for the change, there are similar ones for bitbucket, where several examples payloads are tested against the server endpoint with a mock client and assert that mocked instances of ModuleVersion and GitModuleExtractor are called appropriately? But, if you don't have time and/or don't want to, I'd be happy to write some - just let me know :)
 - If you're happy with the first point, once you reply, I'll push your branch to gitlab and get CI run :)

**Review by MatthewJohn — CHANGES_REQUESTED** [review]

**Comment by MatthewJohn** [comment]
> @MatthewJohn If this name/url change is undesirable I am happy to remove those changes from this PR

@Davidsoff Given it was originally required for manual consumption, for me, this is fine - I'll bump the major version since it's a breaking change, but that's fine :)

**Comment by Davidsoff** [comment]
Thanks for the feedback! It's been a crazy week so haven't had much time to look at it yet

> @Davidsoff First of all, I can't believe how many typos of analytics there are :D My muscle memory is truly broken for this word :( But, thank you so much for this - it all looks great :)

Haha no worries, after I found one it was a simple search&replace ;)

> Couple of notes:
> 
> * I'm sure you saw in the README/contributing, but the project might need to switch to another license (GPL or LGPL). Could you state a comment that you're happy if this happens (assuming that you are) and you agree that the changes you've contributed can also change in license to GPL/LGPL? :)

Yep happy to contribute to GPL/LGPL

> * I think some unit tests would be needed for the change, there are similar ones for bitbucket, where several examples payloads are tested against the server endpoint with a mock client and assert that mocked instances of ModuleVersion and GitModuleExtractor are called appropriately? But, if you don't have time and/or don't want to, I'd be happy to write some - just let me know :) (for reference, here are the bitbucket hook tests: https://github.com/MatthewJohn/terrareg/blob/main/test/unit/terrareg/server/test_api_module_provider_bitbucket_hook.py)

I'll see if I can have a look at those tomorrow
> * If you're happy with the first point, once you reply, I'll push your branch to gitlab and get CI run :)

Let me get the updated tests in first before doing those pushes.
Saves you the trouble of having to do this multiple times ;)

**Comment by MatthewJohn** [comment]
Thanks @Davidsoff  :) I've created a PR to your fork with some test updates and a couple of suggestions :) Feel free pull in whatever you want from that

**Comment by Davidsoff** [comment]
> Thanks @Davidsoff :) I've created a PR to your fork with some test updates and a couple of suggestions :) Feel free pull in whatever you want from that

Awesome!!!! Thanks for the help. All changes look like they should do what you'd expect of them so I added them to the PR.

**Comment by MatthewJohn** [comment]
Thank you :D I'll pull your branch into a branch in the upstream and create a PR

**Comment by MatthewJohn** [comment]
> Thank you :D I'll pull your branch into a branch in the upstream and create a PR

Have created https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/207

**Comment by MatthewJohn** [comment]
I've merged the PR in Gitlab - it should replicate to github shortly and automatically show the PR as merged.

Thank you again for your implementation of this, I really appreciate it :)

Not sure if you're using Terrareg for anything, or just saw the opportunity to contribute, but _if_ the former, I hope it's providing some use and you're finding it okay :)

**Comment by MatthewJohn** [comment]
I've merged the PR in Gitlab - it should replicate to github shortly and automatically show the PR as merged.

@Davidsoff Thank you again for your implementation of this, I really appreciate it :)

Not sure if you're using Terrareg for anything, or just saw the opportunity to contribute, but _if_ the former, I hope it's providing some use and you're finding it okay :)

**Pull request merged**
