### PR TITLE
Security fixes

### PR DESCRIPTION
**Pull request by AlexanderWiechert**
reduce vulnerabilities

### CODE REVIEW

**Comment by MatthewJohn** [comment]
Hey @AlexanderWiechert

Thank you for this :) We recently bumped a bunch of dependencies (which is why there's a merge conflict) - would you be able to rebase from main and see what remains? :) 

Matt

**Comment by AlexanderWiechert** [comment]
Hey Matt,

sure I‘ll check it from there.

—Alex
Am 5. Okt. 2023, 21:24 +0200 schrieb Matt John ***@***.***>:

**Comment by AlexanderWiechert** [comment]
Hi Matt, I'm done.

**Comment by MatthewJohn** [comment]
Thank you :) I've created a a PR https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/364 - will let the tests run and will merge once they look good :)

**Comment by MatthewJohn** [comment]
Hey :) This was merged - though I think the last merge you did caused Github to not be able to recognise the merge, so will need to manually close :)

Thank you for these :)

Matt

**Pull request closed without merging**
