### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by bmaximuml**
repsonse -> response

### CODE REVIEW

**Comment by MatthewJohn** [comment]
Thanks you :)
I'll take this commit, but will need to prefix the commit message to fit our CI/CD pipeline and get that merged :)

Many thanks :)
Matt

**Comment by MatthewJohn** [comment]
I've created a PR: https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/346
Will merge once CI has passed :)

Thanks again :)
Matt

**Comment by bmaximuml** [comment]
Thanks @MatthewJohn

**Comment by MatthewJohn** [comment]
This has now been merged (https://github.com/MatthewJohn/terrareg/commit/37de4cf35360f756f5b21aa4705bf19b84bd5b85) and released in 2.73.1 (https://github.com/MatthewJohn/terrareg/commit/774119bb20ecfe6609f3728f01098c58b72fb3da)

Thanks again :)

**Pull request closed without merging**
