### PR TITLE
fix: Update mktemp to use NamedTemporaryFile

### PR DESCRIPTION
**Pull request by mark-jones-rga**

### CODE REVIEW

**Comment by MatthewJohn** [comment]
Have created https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/437
Just waiting for CI to run :)

**Comment by MatthewJohn** [comment]
It's all passed - the only thing I'm wondering about is whether, since it _only_ affects the test code, which isn't (at least shouldn't be) run during normal execution whether this can be marked as a "test: " commit, rather than "fix: ".
How would you feel about this?

Matt

**Comment by mark-jones-rga** [comment]
> It's all passed - the only thing I'm wondering about is whether, since it _only_ affects the test code, which isn't (at least shouldn't be) run during normal execution whether this can be marked as a "test: " commit, rather than "fix: ". How would you feel about this?
> 
> Matt

Yes that's fine. I'm actually going to close this one and resubmit under my personal.  Had some info in commits I need to keep in house.

**Comment by MatthewJohn** [comment]
> > It's all passed - the only thing I'm wondering about is whether, since it _only_ affects the test code, which isn't (at least shouldn't be) run during normal execution whether this can be marked as a "test: " commit, rather than "fix: ". How would you feel about this?
> > Matt
> 
> Yes that's fine. I'm actually going to close this one and resubmit under my personal. Had some info in commits I need to keep in house.

Sure, no problem :)

**Pull request closed without merging**
